In [1]:
## Dataset with  690 obs. of  15 features:
##  $ f0 : Factor w/ 2 levels "a","b" (Male)
##  $ f1 : num  30.8 58.7 24.5 27.8 20.2 ..(Age)
##  $ f2 : num  0 4.46 0.5 1.54 5.62.. (Debt)
##  $ f3 : Factor w/ 3 levels "l","u","y" (Married)
##  $ f4 : Factor w/ 3 levels "g","gg","p" (BankCustomer)
##  $ f5 : Factor w/ 14 levels "aa","c","cc" (EducationLevel)
##  $ f6 : Factor w/ 9 levels "bb","dd","ff" (Ethnicity)
##  $ f7 : num  1.25 3.04 1.5 3.75 1.71... (YearsEmployed)
##  $ f8 : Factor w/ 2 levels "f","t" (PriorDefault)
##  $ f9: Factor w/ 2 levels "f","t" (Employed)
##  $ f10: int  1 6 0 5 0 0 0 0 0 0 ... (CreditScore)
##  $ f11: Factor w/ 2 levels "f","t" (DriversLicense)
##  $ f12: Factor w/ 3 levels "g","p","s" (Citizen   )
##  $ f13: int  202 43 280 100 120 360 164 80 180 52 ...(Zipcode)
##  $ f14: int  0 560 824 3 0 0 31285 1349 314 1442 ... (Income)
##  $ f15: Factor w/ 2 levels "-","+"  (Approved)

In [2]:
import numpy as np
import pandas as pd

In [3]:
rawdata = pd.read_csv('Dataset/crx.data',header=None)

In [4]:
37/690*100

5.36231884057971

In [5]:
rawdata.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [6]:
# Removing the missing values
miss_index = []
for col in rawdata.columns:
    miss_index.extend(list(rawdata[rawdata[col]=="?"].index.values))
    
data = rawdata.drop(miss_index, axis=0)

/home/gabi/deepenv/lib/python3.7/site-packages/pandas/core/ops/__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


In [7]:
# Number of Missing Values
n_missval = len(rawdata)-len(data)

In [8]:
from collections import defaultdict
from sklearn.preprocessing import LabelEncoder

d = defaultdict(LabelEncoder)

# Encoding the necessary features(0,3,4,5,6,8,9,11,12,15)
enc = data[[0,3,4,5,6,8,9,11,12,15]].apply(lambda x: d[x.name].fit_transform(x))

In [9]:
enc

0   3   4   5   6   8   9   11  12  15
0     1   1   0  12   7   1   1   0   0   0
1     0   1   0  10   3   1   1   0   0   0
2     0   1   0  10   3   1   0   0   0   0
3     1   1   0  12   7   1   1   1   0   0
4     1   1   0  12   7   1   0   0   2   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
685   1   2   2   4   3   0   0   0   0   1
686   0   1   0   1   7   0   1   1   0   1
687   0   2   2   5   2   0   1   1   0   1
688   1   1   0   0   7   0   0   0   0   1
689   1   1   0   1   3   0   0   1   0   1

[653 rows x 10 columns]

In [10]:
data[15].value_counts()

-    357
+    296
Name: 15, dtype: int64

In [11]:
# Converting to float numbers

data = data[[1,2,7,10,13,14]].astype(float)

In [12]:
data.head()

1      2     7    10     13     14
0  30.83  0.000  1.25  1.0  202.0    0.0
1  58.67  4.460  3.04  6.0   43.0  560.0
2  24.50  0.500  1.50  0.0  280.0  824.0
3  27.83  1.540  3.75  5.0  100.0    3.0
4  20.17  5.625  1.71  0.0  120.0    0.0

In [13]:
data3 = pd.concat([data,enc],axis=1,sort=True)
data3.head()

1      2     7    10     13     14  0   3   4   5   6   8   9   11  12  \
0  30.83  0.000  1.25  1.0  202.0    0.0   1   1   0  12   7   1   1   0   0   
1  58.67  4.460  3.04  6.0   43.0  560.0   0   1   0  10   3   1   1   0   0   
2  24.50  0.500  1.50  0.0  280.0  824.0   0   1   0  10   3   1   0   0   0   
3  27.83  1.540  3.75  5.0  100.0    3.0   1   1   0  12   7   1   1   1   0   
4  20.17  5.625  1.71  0.0  120.0    0.0   1   1   0  12   7   1   0   0   2   

   15  
0   0  
1   0  
2   0  
3   0  
4   0

In [14]:
data3 = data3.reindex(sorted(data3.columns), axis=1).values

In [16]:
data3

array([[1.000e+00, 3.083e+01, 0.000e+00, ..., 2.020e+02, 0.000e+00,
        0.000e+00],
       [0.000e+00, 5.867e+01, 4.460e+00, ..., 4.300e+01, 5.600e+02,
        0.000e+00],
       [0.000e+00, 2.450e+01, 5.000e-01, ..., 2.800e+02, 8.240e+02,
        0.000e+00],
       ...,
       [0.000e+00, 2.525e+01, 1.350e+01, ..., 2.000e+02, 1.000e+00,
        1.000e+00],
       [1.000e+00, 1.792e+01, 2.050e-01, ..., 2.800e+02, 7.500e+02,
        1.000e+00],
       [1.000e+00, 3.500e+01, 3.375e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00]])

In [15]:
data3

array([[1.000e+00, 3.083e+01, 0.000e+00, ..., 2.020e+02, 0.000e+00,
        0.000e+00],
       [0.000e+00, 5.867e+01, 4.460e+00, ..., 4.300e+01, 5.600e+02,
        0.000e+00],
       [0.000e+00, 2.450e+01, 5.000e-01, ..., 2.800e+02, 8.240e+02,
        0.000e+00],
       ...,
       [0.000e+00, 2.525e+01, 1.350e+01, ..., 2.000e+02, 1.000e+00,
        1.000e+00],
       [1.000e+00, 1.792e+01, 2.050e-01, ..., 2.800e+02, 7.500e+02,
        1.000e+00],
       [1.000e+00, 3.500e+01, 3.375e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00]])

In [14]:
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [15]:
kf = KFold(n_splits=10, shuffle=True, random_state=10)

In [16]:
dtree = DecisionTreeClassifier()

In [17]:
for train_index, test_index in kf.split(data3):
    train, test = data3[train_index], data3[test_index]
    
    x_train, x_test = train[:,:14], test[:,:14]
    y_train, y_test = train[:,15], test[:,15]
    
    dtree.fit(x_train,y_train)
    predictions = dtree.predict(x_test)
    print(confusion_matrix(y_test,predictions))
    print('\n')
    print(classification_report(y_test,predictions))

[[26  4]
 [11 25]]


              precision    recall  f1-score   support

         0.0       0.70      0.87      0.78        30
         1.0       0.86      0.69      0.77        36

    accuracy                           0.77        66
   macro avg       0.78      0.78      0.77        66
weighted avg       0.79      0.77      0.77        66

[[30  7]
 [ 3 26]]


              precision    recall  f1-score   support

         0.0       0.91      0.81      0.86        37
         1.0       0.79      0.90      0.84        29

    accuracy                           0.85        66
   macro avg       0.85      0.85      0.85        66
weighted avg       0.86      0.85      0.85        66

[[21  6]
 [ 5 34]]


              precision    recall  f1-score   support

         0.0       0.81      0.78      0.79        27
         1.0       0.85      0.87      0.86        39

    accuracy                           0.83        66
   macro avg       0.83      0.82      0.83        66
weighted av

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
rfc = RandomForestClassifier(n_estimators=200)

In [24]:
for train_index, test_index in kf.split(data3):
    train, test = data3[train_index], data3[test_index]
    
    x_train, x_test = train[:,:14], test[:,:14]
    y_train, y_test = train[:,15], test[:,15]
    
    rfc.fit(x_train,y_train)
    predictions = rfc.predict(x_test)
    print(confusion_matrix(y_test,predictions))
    print('\n')
    print(classification_report(y_test,predictions))

[[27  3]
 [ 7 29]]


              precision    recall  f1-score   support

         0.0       0.79      0.90      0.84        30
         1.0       0.91      0.81      0.85        36

    accuracy                           0.85        66
   macro avg       0.85      0.85      0.85        66
weighted avg       0.86      0.85      0.85        66

[[31  6]
 [ 2 27]]


              precision    recall  f1-score   support

         0.0       0.94      0.84      0.89        37
         1.0       0.82      0.93      0.87        29

    accuracy                           0.88        66
   macro avg       0.88      0.88      0.88        66
weighted avg       0.89      0.88      0.88        66

[[24  3]
 [ 8 31]]


              precision    recall  f1-score   support

         0.0       0.75      0.89      0.81        27
         1.0       0.91      0.79      0.85        39

    accuracy                           0.83        66
   macro avg       0.83      0.84      0.83        66
weighted av

In [10]:
from sklearn import svm

In [11]:
model = svm.SVC()

In [12]:
model

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)